### ISSUE TITLE
Soothing Lantern don't work

### ISSUE THREAD

**Issue by aarontf** [HyperPigeon/Eldritch-Mobs#24]
I have placed soothing lanterns in every chunk of my vanilla enderman farm, yet eldritch endermen still spawn.

**Comment by aarontf** [comment]
Update, looking at the code it is all commented out so it works nowhere.

**Comment by HyperPigeon** [comment]
I've updated the mod to a newer version of fabric API and the soothing lanterns appear to be working properly now. Also, the soothing lantern does not rely on the code I commented out, so that shouldn't be the crux of the issue. 

I'll be doing a few more bug tests before I release the update, and hopefully, that fixes your problem.

**Comment by HyperPigeon** [comment]
Fixed in the latest release.
