### ISSUE TITLE
/Summon_<tier> has chance to summon higher tiers

### ISSUE THREAD

**Issue by milkev** [HyperPigeon/Eldritch-Mobs#36]
when using the commands to summon mobs, the resulting mob might be a higher tier than what you summoned it as

ie:
using /summon_elite <mob> with the config for ultras's out of elites as 100% would always spawn ultras, and the summon elite command would be unable to summon an elite

**Comment by Julveria** [comment]
It's because of the settings. In this case you put the rate of ultras out of elites as 100%. That means every single elites will be ultras. Relatively simple percentage concept.

**Comment by milkev** [comment]
im saying that the command shouldnt summon tiers you arent selecting with the command. its just plain annoying to do /summon_elite and get an eldritch or ultra

**Comment by Julveria** [comment]
I get what you're saying, but like the higher tier is chance based on the lower tiers. Say, the default config is 1% for each tier. That means each time you summon a buffed mob, there's a 1 percent CHANCE it will be a higher tier, might be an ultra or eldritch. I think this is completely intentional, and you have like insane luck to get that to happen.

**Comment by milkev** [comment]
if you have modified chances than it can be extremely easy to get them, either way its not a high priority fix, but it would be a nice one nonetheless

**Comment by HyperPigeon** [comment]
Fixed in the update to 1.19.
