### ISSUE TITLE
[Suggestion] Damage Modifiers

### ISSUE THREAD

**Issue by milkev** [HyperPigeon/Eldritch-Mobs#37]
Is it possible to add damage modifiers for elite/ultra/eldritch mobs?

personally i find that simply increasing mobs HP doesnt really make them any more dangerous, even with a lot of the special effects. But being able to increase their damage would make them pose a more significant threat to both early and late game players, being very dangerous to get hit by early game, and still able to damage you in the late game (where most mobs cant do anything to you)

**Comment by HyperPigeon** [comment]
Do you mean the damage that mobs do when they hit you normally or the damage that they do with their abilities?

**Comment by milkev** [comment]
both could work, though i was primarily thinking their normal attack damage (such as through a strength effect)

**Comment by HyperPigeon** [comment]
Sounds feasible. Thank you for the clarification. 

Also as a side note, I'm planning on completely re-coding the mod in the future since I made this mod when I was quite new to modding and didn't really know what I was doing. Some of your suggestions may not be plausible with the current system I have in place, but might be easier to implement after the code re-design.

**Comment by HyperPigeon** [comment]
Added in the latest release.
